server:
  port: 8090

spring:
  application:
     name: proveedores

  profiles:
    active: test

# Habilitación técnica de OpenAPI y Swagger UI para Proveedores

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/


